### ISSUE TITLE
Is bool Publisher::publish( const Event& event ) deprecated?

### ISSUE THREAD

**Issue by ptoharia** [HBPVIS/ZeroEQ#135]
Hi, 

In the doxygen documentation it says it is deprecated but it doesn't dump deprecation message through ZEQWARN as the servus::URI-based constructor does. 

Thanks,
Pablo.

**Comment by tribal-tec** [comment]
Yes, the flatbuffer-based APIs are deprecated. I guess there are no warnings printed to avoid the noise right now. We will schedule a cleanup session soon hopefully to get rid of the servus::URI and flatbuffers code.
