### ISSUE TITLE
http server may hang in receive() when remote connection is closed abruptly

### ISSUE THREAD

**Issue by rdumusc** [HBPVIS/ZeroEQ#157]
The application deadlocks at ::zmq::send() at lines 195-197 of server.cpp trying to send a return code 200:
```
if( ::zmq_send( socket, id, idSize, ZMQ_SNDMORE ) != idSize ||
        ::zmq_send( socket, rep.c_str(), rep.length(), more ) !=
        int( rep.length( )))
{
ZEROEQWARN << "Could not send HTTP response header: "
                          << zmq_strerror( zmq_errno( )) << std::endl;
return;
}
```

**Comment by tribal-tec** [comment]
Setting ZMQ_LINGER to something low or even 0 is one fix. ZMQ_NOBLOCK could as well, but appears to have issue on closing the socket:
http://stackoverflow.com/questions/7538988/zeromq-how-to-prevent-infinite-wait

**Comment by tribal-tec** [comment]
Thanks to @favreau for testing. ZMQ_NOBLOCK seems to do the trick. Will attack this next week and try to add test for it :)

**Comment by favreau** [comment]
Thanks @tribal-tec ! :)
